---

- hosts: all
  become: true
  tasks:
    - name: update server
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: install apache2 package
      ansible.builtin.apt:
        name: apache2
        state:  absent

    - name: add php support for apache
      ansible.builtin.apt:
        name: libapache2-mod-php
        state: absent
